spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sb_25_01_dev
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:h2:./sb_25_01_dev;MODE=MySQL
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
logging:
  level:
    com.ll.sb231127: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE