spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sb_25_01_dev
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:./sb_25_01_dev;MODE=MySQL
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver